format = """
[╭─](fg:#b4befe)\
[  ](bg:#b4befe fg:#090c0c)\
[](bg:#7c86ff fg:#b4befe)\
$directory\
[](fg:#7c86ff bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#313244)\
$time\
[ ](fg:#313244)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#7c86ff"
format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#313244"
format = '[[  $time ](fg:#a0a9cb bg:#313244)]($style)'

[character]
success_symbol = '[╰─](fg:#b4befe)'
error_symbol = '[╰─](fg:#b4befe)'
